### ISSUE TITLE
GunStation not working.

### ISSUE THREAD

**Issue by FrostBeertje** [PlanatedLlama45/gun_datapack#1] opened 2024-01-09 11:12 UTC
Good afternoon,

I have a question regarding the Gun station, It doesn't seem to work when I drop items on it. It basically looks like a oak plank block with a barrier on top of it in an invisible item frame.

Now here lies my question, Am I doing something wrong, do I have to power it some way, I can't seem to find any info on it. I'm unable to interact with it and dropping items doesn't do anything aswell.

Thanks in advance for the help.

Kind regards
FrostBeertje

**Comment by PlanatedLlama45** [comment] 2024-01-09 20:24
## Why it looks like that
It seems that you haven't installed/enabled the required resourcepack:
![image](https://github.com/PlanatedLlama45/gun_datapack/assets/79642040/3b0771b7-70df-4c68-be69-1ef10cf12780)
(this thing)

The station should look like this:
![image](https://github.com/PlanatedLlama45/gun_datapack/assets/79642040/1c1e8034-cf16-4c76-8345-1695dde99817)

## Why it doesn't work
It depends what version of the datapack you have. In the first version (0.1) I managed to make the Gun Station inconsistent and bugged. If you have this version, then the solution would be to update to the latest one.

That is the most likely problem, however, if you have the latest version (0.1.1), please write back as right now this is the only idea I have as to why this doesn't work. It also would be helpful if you sent screenshots. 

P.S. You don't need to power it. You just drop items on top of it.

<br/>
Apologies if this wasn't helpful.

**Comment by PlanatedLlama45** [comment] 2024-01-27 10:01
This bug has been fixed in v0.2.1.
Although in my defense it worked perfectly fine in my main testing world so I could only reproduce it when making screenshots in my other world.

**Closed as completed** 2024-01-27 10:01 UTC
